### ISSUE TITLE
Operator removes other annotations

### ISSUE THREAD

**Issue by prankstr** [1Password/onepassword-operator#112]
### Your environment

Operator Version: 1.4.1

Connect Server Version: 1.5.1

Kubernetes Version: 1.23.6

## What happened?

When the 1Password operator updates my deployment with an annotation such as operator.1password.io/last-restarted it also removes other annotations that isn't related to 1Password, it my case prometheus annotations so monitoring stopped working.

## What did you expect to happen?

I would expect 1Password to carry over all annotations when updating or don't do anything with annotations other than the ones for the 1password operator.

## Steps to reproduce
1. Make sure operator is set to restart deployments when secrets are updated.

2: Deploy something with annotations and that uses a secret from one password somehow, my setup was as follows:
```
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
```
```
 env:
   - name: PASSWORD
     valueFrom:
       secretKeyRef:
         key: password
         name: secret
```
```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: secret
spec:
  itemPath: "vaults/vault/items/secret" 
```

3: Update the secret and verify the annotations of the new deploy/pod, the prometheus annotations is now removed and  my annotations have been replaced with just:
```
metadata:
  annotations:
    operator.1password.io/last-restarted: 2022-05-13 13:26:32.706427774 +0000 UTC
      m=+24.598641040
```
