### ISSUE TITLE
Add custom annotations to Secrets

### ISSUE THREAD

**Issue by vhemt** [1Password/onepassword-operator#114]
### Summary
Provide a way to add custom annotations to Secrets.

### Use cases
I need to create a webhook to execute certain actions when a Secret is modified. I need some additional information to decide what do to. 
Annotations would be the best way to pass that information.

### Proposed solution
The implementation has been added and removed in the last months. 
It should be basically reverting this PR: https://github.com/1Password/onepassword-operator/pull/104 or reimplementing it only copying specific annotations, prefixed in a certain way or something similar.

### Is there a workaround to accomplish this today?
Not that I'm aware of. The only way to pass additional information is to use the Secret name, but the character limit doesn't allow me to achieve what I want.

**Comment by hudymi** [comment]
Actually, because of that, we cannot use 1Password in our integration, as some of the components are expecting particular annotations. If you don't want to copy generated annotations as mentioned in #104, then please do something like:

```yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: some-secret
  namespace: exampe
spec:
  metadata:
    annotations:
      example-annotation: that-will-be-propagated-to-secret
  itemPath: vaults/exampe/items/some-secret
type: kubernetes.io/dockerconfigjson
```

Similarly, labels can be moved, but please do that with a deprecation period.
