### ISSUE TITLE
Be able to rename keys from 1Password

### ISSUE THREAD

**Issue by Xorima** [1Password/onepassword-operator#128]
### Summary
The keys in the secrets come directly from 1password, there are times at which changing these key names is very desirable. 

### Use cases

ArgoCD wants to consume a [secret in a well known format](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories) to be able to connect via ssh to a repository. 

1Password has a `SSH Key` secret type which is stronly opinionated that the private key is stored in a field called `private key` and is not renamable. 

To be able to resolve this (and I am sure there are other times at which removing the hard coupling between field name and secret key) I want to be able to say that key name: `private key` should be put in the secret as `sshPrivateKey` 

### Proposed solution

Extend the `OnePasswordItem` `spec` to have a `keyMutation` property which would allow us to do to/from today but also enable further changes down the line if desired (such as a regex match for large scale changes across a lot of values at once). 
If a different name than `keyMutation` was selected we could also use that to enforce that certian keys must exist else the operator would error to reduce human error

This would look like: 

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: example
spec:
  itemPath: "vaults/<vault_id>/items/<item_id>"
  keyMutation:
    - key: "private key"
       action: rename
       value: `sshPrivateKey`
```

I cannot currently think of other `actions` to perform but I feel by leaving this in there (or maybe leaving it as a documented default) then if other usecases come up this could easily be extended to those usecases. 

### Is there a workaround to accomplish this today?

You can store ssh keys outside of the ssh key object in 1password, but you then lose all the value given by that key type, such as the `fingerprint` and the `public key` being just given to you, so if you update the key you would need to ensure you update everything accurately 

### References & Prior Work
https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar#apply-a-template-to-the-injected-secrets
