### ISSUE TITLE
Operator no longer includes annotations within the created secret

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/onepassword-operator#144]
### Your environment

Operator Version: v1.6.0

Connect Server Version: 1.5.7

Kubernetes Version: 1.23.9

## What happened?

In version 1.3.0 of the operator, any annotation I added to the operator would be propagated to the resulting secret. Now, none of my annotations are added.

## What did you expect to happen?

I expected the resulting secret to have the annotations I set

## Steps to reproduce
1.  Create a OnePasswordItem with annotations
2. Deploy
3. Validate the resulting secret doesn't have annotations
4. Use v1.3.0 of the operator
5. Do steps 1-3
6. Validate annotations are there

## Notes & Logs

```
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    kubed.appscode.com/sync: "true"
```
```
kind: Secret
metadata:
  annotations:
    operator.1password.io/item-path: vaults/***/items/***
    operator.1password.io/item-version: "3"
```
