### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by robb-j** [1Password/onepassword-operator#149]
### Your environment

Operator Version: 1.5.7

Connect Server Version: 1.5.7?

Kubernetes Version: v1.23.14

## What happened?

The memory usage of my `onepassword-connect` pod was 1097Mi which seems very high, is there a normal amount of memory this container should stay around?

## What did you expect to happen?

I thought the container would need a lot less memory 

## Steps to reproduce

1. The container had been running for 38 days, after restarting the container it was using around 30Mi of memory.
   This is on a really small cluster with only 8 OnePasswordItem resources in it.
2. The memory seems to go up a few `Mi` every few minute

## Notes & Logs

**before restarting**
<img width="682" alt="before" src="https://user-images.githubusercontent.com/1526174/212494481-355d21c2-8fbc-4449-9f78-6079d8203678.png">

**after restarting**
<img width="607" alt="after" src="https://user-images.githubusercontent.com/1526174/212494484-aa71f878-3667-4dad-9227-08ae78b3c950.png">

my `values.yml` passed to helm:

```yml
operator:
  create: true
  watchNamespace: [r0b-system,games,default,tools,hyem-tech]
```

**Comment by mhixon4479** [comment]
Seeing similar here. The pod itself isn't being actively used although memory seems to leak until it's OOM killed.

<img width="945" alt="Screen Shot 2023-01-25 at 9 07 20 AM" src="https://user-images.githubusercontent.com/101131697/214631881-6aa569d3-5b7d-4868-88e1-0e6c3dad079f.png">

**Comment by katherine-black** [comment]
Its a shame there are not default values included for the resources requests/limits in the helm chart.

**Comment by gladiatr72** [comment]
hrm.  has this been resolved with newer versions?  I set up a goldilocks monitor for it yesterday and am getting this as a resources recommendation:

```
resources:
  requests:
    cpu: 163m
    memory: 2282M
  limits:
    cpu: 163m
    memory: 2282M
```
