### ISSUE TITLE
[Feature Request] Enable creating multiple 1Password secrets using deployment annotations

### ISSUE THREAD

**Issue by edif2008** [1Password/onepassword-operator#159]
### Summary

It would be great to be able to create multiple secrets from 1Password using annotations.

This is based on [this customer's feedback](https://1password.community/discussion/137950/how-can-i-create-multiple-secrets-from-the-same-vault-using-deployment-annotations#latest).

This attempt doesn't work since the map keys have to be unique.
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    operator.1password.io/item-path: "vaults/test-k8s-cluster/items/nine-nine-test-secret"
    operator.1password.io/item-name: "nine-nine-test-secret"
    operator.1password.io/item-path: "vaults/test-k8s-cluster/items/demo-micro-configuration"
    operator.1password.io/item-name: "demo-micro-configuration"
``` 

### Use cases

A deployment may need secrets that are stored in multiple 1Password items. To have the scope narrowed down, one would prefer to provide the secrets needed for a deployment as annotations.

### Is there a workaround to accomplish this today?

Create the secrets using `OnePasswordItem` resources instead.

**Comment by bdsoha** [comment]
I have come across the same issue and was contemplating whether it is correct to *aggregate* all deployment credentials into a single secret.
IMO, it is a better practice to split secrets based on single use.

A suggested solution would be to append a suffix the `annotation`, something like:

```yaml
metadata:
  annotations:
    operator.1password.io/item-path/0: "vaults/test-k8s-cluster/items/nine-nine-test-secret"
    operator.1password.io/item-name/0: "nine-nine-test-secret"
    operator.1password.io/item-path/1: "vaults/test-k8s-cluster/items/demo-micro-configuration"
    operator.1password.io/item-name/1: "demo-micro-configuration"
```

**Comment by andreasgrob** [comment]
An even less verbose option would be to include the item name in the key:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  annotations:
    operator.1password.io/item-path/SECRET_NAME1: "vaults/VAULT/items/ITEM1"
    operator.1password.io/item-path/SECRET_NAME2: "vaults/VAULT/items/ITEM2"
    operator.1password.io/item-path/SECRET_NAME3: "vaults/VAULT/items/ITEM3"
```
