### ISSUE TITLE
Allow to specify the type of the secret created by the OnePasswordItem

### ISSUE THREAD

**Issue by rhaex** [1Password/onepassword-operator#165]
### Summary
Allow to specify the type of secret in the OnePasswordItem.

### Use cases
When executing deployments form a tool like ArgoCD, where you create your configuration from git based on Kustomize and let ArgoCD create the namespace etc you currently cannot start it automatically if you use a private Docker registry. This is because you need to set the pull-secret.
This is very easy to add to the deployments, and stored in 1Password and add as a OnePasswordItem. However, this secret does not work as it is added as type `Opaque` instead of `kubernetes.io/dockerconfigjson`.

### Proposed solution
Be able to set the secret type as a property on the OnePasswordItem.

### Is there a workaround to accomplish this today?
No

**Comment by tomjohnburton** [comment]
You already can
```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    argocd.argoproj.io/instance: secrets
  name: dockerconfigjson
spec:
  itemPath: vaults/cluster-global/items/dockerconfigjson
type: kubernetes.io/dockerconfigjson

```

**Comment by rhaex** [comment]
I see, I tried that and indeed that works. I don't remember seeing that in the documentation, and I just checked it and I can't find it anywhere there.
The documentation seems to lack this information, so possibly there are more "hidden" features that might be added to the docs.
Thanks for your help @tomjohnburton !

**Comment by cessien** [comment]
@rhaex @tomjohnburton what type of secret/field is supposed to be set in onepassword itself? For this to work? I'm on latest versions + crds and I keep getting a status:

```
status:
  conditions:
    - lastTransitionTime: '2023-09-10T15:33:15Z'
      message: >-
        Secret "argocd-image-updater-secret" is invalid:
        data[.dockerconfigjson]: Required value
      status: 'False'
      type: Ready
```

**Comment by thoongnv** [comment]
Just a docs that I have to add a new field: `.dockerconfigjson` (here I used 1Password Document type) to create below `OnePasswordItem`.

```yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: my-secret
spec:
  itemPath: "vaults/my-vault/items/my-secret"
```

![Screenshot 2023-10-31 at 15 32 28](https://github.com/1Password/onepassword-operator/assets/15308084/7db8fd75-ac65-4417-bc49-be1a5760eb84)
