### ISSUE TITLE
Secrets referenced from Projected Volumes are not detected

### ISSUE THREAD

**Issue by mmorejon** [1Password/onepassword-operator#168]
### Your environment

Operator Version: 1.6.0

Connect Server Version: 1.7.0

Kubernetes Version: v1.27.4+k3s1

## What happened?

Secrets added inside Projected Volumes don't trigger a rollout update for pods when the item value is updated in 1Password.
Based on the code, the section `projected` isn't evaluated. [[link](https://github.com/1Password/onepassword-operator/blob/main/pkg/onepassword/volumes.go#L7)]
Volume structure in Kubernetes [[link](https://kubernetes.io/docs/concepts/storage/projected-volumes/)]

## What did you expect to happen?

Pods should be recreated when the item value change.

## Steps to reproduce
1. Create an item in 1Password with name `secret-02` and key `hidden-place`
2. Create the following resources in k8s.

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: secret-02
spec:
  itemPath: "vaults/rpi/items/secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secret-02
  labels:
    app: secret-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-02
  template:
    metadata:
      labels:
        app: secret-02
    spec:
      containers:
        - name: container-01
          image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
          imagePullPolicy: IfNotPresent
      volumes:
        - name: all-in-one
          projected:
            sources:
            - secret:
                name: secret-02
                items:
                  - key: hidden-place
                    path: hidden-place
```
3. Change the `hidden-place` value in 1Password.

## Notes & Logs

No logs
