### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lhriley** [1Password/onepassword-operator#180]
### Your environment

Operator Version: 1.8.0

Connect Server Version: 1.7.2

Kubernetes Version:

```
❯ kubectl version --output=yaml
clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-07-17T09:25:02Z"
  compiler: gc
  gitCommit: 2ce07bca20da6c3fa49a26fe8e5d53cb8a1e073f
  gitTreeState: clean
  gitVersion: v1.27.3-gke.1700
  goVersion: go1.20.5 X:boringcrypto
  major: "1"
  minor: "27"
  platform: linux/amd64
```

## What happened?

Operator pod panics with the following error after recreating the pod:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137f5b0]
```

## What did you expect to happen?

The operator doesn't panic.

## Steps to reproduce
1. `kubectl delete -n onepassword-connect onepassword-connect-operator-abc123-xyz987`

## Notes & Logs

```
❯ kubectl -n onepassword-connect logs -f onepassword-connect-operator-855584b64b-qgh2j
2023-12-04T23:40:27Z    INFO    setup   Operator Version: 1.8.0
2023-12-04T23:40:27Z    INFO    setup   Go Version: go1.20.7
2023-12-04T23:40:27Z    INFO    setup   Go OS/Arch: linux/amd64
2023-12-04T23:40:27Z    INFO    setup   Version of operator-sdk: 1.29.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137f5b0]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
        /workspace/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00004af78, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        /workspace/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:95 +0x6f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000532390, 0x15}, {0xc00004e980, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        /workspace/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:49 +0x125
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0001b6c80?)
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0001b70b0?)
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery.ServerGroupsAndResources({0x1afd738, 0xc0000dc810})
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:413 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:376 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc0005af0c8)
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:651 +0x71
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
        /workspace/vendor/k8s.io/client-go/discovery/discovery_client.go:375 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x1afd738?, 0xc0000dc810?})
        /workspace/vendor/k8s.io/client-go/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc0001a6360?, {0x0, 0x0, 0xfa3b126c3890da01?})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc0001df500?)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc000296b40, {0xc0001b7a70, 0x1, 0x0?})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0001df500, 0x0, 0x0, {{0x1af9e40, 0xc00040b580}, 0x0}, 0x0, {0x0, 0x0}, ...})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:351 +0xf9
main.main()
        /workspace/main.go:144 +0x535
```
