### ISSUE TITLE
Using with Helm

### ISSUE THREAD

**Issue by nodesocket** [1Password/onepassword-operator#19]
I am currently using standard Helm and a template like:

```
{{- $def := index .Values "default" -}}
apiVersion: v1
data:
  STRIPE_PUBLIC_KEY: {{ default $def.STRIPE_PUBLIC_KEY | b64enc }}
  STRIPE_SECRET_KEY: {{ default $def.STRIPE_SECRET_KEY | b64enc }}
  # .... etc ....
kind: Secret
metadata:
  name: api-env
type: Opaque
```

Then the deployment simply does:

```
envFrom:
        - secretRef:
            name: api-env
```

How would migrating to 1Password-operator in our Kubernetes cluster work?

**Comment by florisvdg** [comment]
1. Move the secrets from your `values.yaml` to a 1Password vault
2. Set up [1Password Secrets Automation](https://start.1password.com/integrations/connect) for that vault
3. Use the [Helm chart](https://github.com/1password/connect-helm-charts) to deploy Connect+operator
4. For every secret you want to make available in your Kubernetes cluster, add a `OnePasswordItem` CRD where you specify which 1Password item should map to which Kubernetes Secret.

And all your deployment specs can stay the same if they were using Kubernetes Secrets already.

**Comment by nodesocket** [comment]
@florisvdg thanks for the help.

I have completed steps 1, 2, 3.

```
ubuntu@kubectl:/tmp$ kubectl get pods
NAME                                   READY   STATUS             RESTARTS   AGE
onepassword-connect-57bcf96ff8-vzvt6   2/2     Running            0          6m8s
```

When trying to store the CRD though, I am getting the following error::

```
ubuntu@kubectl:/tmp$ kubectl create -f test-onepassword-secret.yaml
error: unable to recognize "test-onepassword-secret.yaml": no matches for kind "OnePasswordItem" in version "onepassword.com/v1"
```

The contents of `test-onepassword-secret.yaml` is:

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: Test Stripe API Key
spec:
  itemPath: "vaults/Acme-Test/items/Test Stripe API Key"
```
