### ISSUE TITLE
support affinity in helm chart

### ISSUE THREAD

**Issue by yalattas** [1Password/onepassword-operator#190]
### Summary
Its much simpler to use affinity to schedule pod to a dedicate NodePool, current chart doesn't have affinity with label

### Use cases
For provisioning pod to a specific NodePool. It will allow to use podAntiAffinity as well to distribute pods across AZs for High-Availability

### Proposed solution
add Affinity in deployment inside helm chart

### Is there a workaround to accomplish this today?
I guess NodeSelector. Havn'e test it yet

### References & Prior Work
```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - critical
```
