### ISSUE TITLE
Operator crashing after the error when constantly retrying

### ISSUE THREAD

**Issue by volodymyrZotov** [1Password/onepassword-operator#203]
### Your environment

Operator Version: 1.8.x

Connect Server Version: This was caught when using service account

Kubernetes Version: `v1.30.0`

## What happened?
After deploying the operator with this resources set in the `./config/manager/manager.yaml`
```
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
```
And reaching rate limits when using service account, the operator pod retries the error immediately and after about a minute the pod is crashing.

## What did you expect to happen?

Operator pod does not crush after a minute when constantly re-trying to handle unrecoverable error.

## Steps to reproduce
1. Create Service Account
2. Replace this:
```
if strings.Contains(err.Error(), "rate limit") {
				reqLogger.V(logs.InfoLevel).Info("1Password rate limit hit. Requeuing after 15 minutes.")
				return ctrl.Result{RequeueAfter: 15 * time.Minute}, nil
			} else {
                            .. . . ....
                         }
```

With 
```
return ctrl.Result{}, err
```
3. Set less resources for pod in the `./config/manager/manager.yaml`
```
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
```
4. In `./config/manager/manager.yaml`  set `imagePullPolicy: Never` to use local image.
5. And set `POLLING_INTERVAL` env var in `manager.yaml` to `1` to pull in 1 minute.
6. Re-build local operator image `make docker-build` 
7. `make deploy` - to deploy your local version
8. Wait until service account reaches rate limits, or do multiple `op item get` or `op vault get` commands using that service account token and 1Password CLI to reach rate limits for that token faster. Use team account so the rate limits are smaller.

## Notes & Logs
This was reproduces when implementing service accounts support https://github.com/1Password/onepassword-operator/pull/198#issuecomment-2954181206
