### ISSUE TITLE
unknown field "operator.1password.io/auto-restart"

### ISSUE THREAD

**Issue by yijiezhen** [1Password/onepassword-operator#32]
Hi, I am trying to use auto-restart in the OnePasswordItem with 1.0.1 with a running operator and connector on k8s, something like below
```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: trulio
  operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/<some-path/" 
```
I am getting
```
error: error validating "item.yaml": error validating data: ValidationError(OnePasswordItem.metadata): unknown field "operator.1password.io/auto-restart" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false
```
Anything I am missing?

**Comment by DWSR** [comment]
Yes, `operator.1password.io/auto-restart` is an annotation, and so belongs in `metadata.annotations`, like this:

```yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: trulio
  annotations:
  	operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/<some-path/" 
```
