### ISSUE TITLE
Support more secret types

### ISSUE THREAD

**Issue by SimonBarendse** [1Password/onepassword-operator#38]
### Summary
Currently the operator only supports `opaque` secrets. It would be good if we support [other types](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) as well.

### Use cases
Among others, to [secure an Ingress with TLS](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) using the TLS secret type.

### Proposed solution

We could add a `type` field to the CRD:
```yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: <type> # One of https://kubernetes.io/docs/concepts/configuration/secret/#secret-types and default to `opaque` when omitted.
metadata:
  name: <item_name> #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/<vault_id_or_title>/items/<item_id_or_title>" 
```

### Is there a workaround to accomplish this today?
Not that I'm aware of.
