### ISSUE TITLE
Report success and error in the OnePasswordItem status field

### ISSUE THREAD

**Issue by OmerKahani** [1Password/onepassword-operator#52]
### Summary
Currently, the only way to understand if the is a reconcile error is by looking at the operator's logs. The status field of the CRD can be used to report errors and success status.

### Use cases
1. A user doesn't have permission to view the logs of the operator
2. ArgoCD can use the status field to report the health status - https://argoproj.github.io/argo-cd/operator-manual/health/#way-2-contribute-a-custom-health-check

### Proposed solution
Add:
```
status:
  conditions:
    - lastTransitionTime:
      message: set secret ...
      status: reconsiled
      type: Ready
    - lastTransitionTime:
      message: Failed to retrieve item...
      status: error
      type: Error
 ```

### Is there a workaround to accomplish this today?
the operator logs

### References & Prior Work
cert manager example: https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateCondition
