### ISSUE TITLE
Support mounting multiple secrets together

### ISSUE THREAD

**Issue by villesau** [1Password/onepassword-operator#59]
### Summary
Would be useful to be able to mount multiple secrets in single secret.

### Use cases
Kubernetes supports following:

Secret definition:

```
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  SECRET_1: "base64"
  SECRET_2: "base64"
```

which is mounted liket this:

```
          envFrom:
            - secretRef:
                name: my-secrets
```

This results in `SECRET_1` & `SECRET_2` being accessible via env variables inside the container.

However, to my understanding 1pw operator can currently carry only 1 field in `my-secrets` so this is not possible.

### Proposed solution

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: testing-secrets #this name will also be used for naming the generated kubernetes secret
spec:
  SECRET_1: "vaults/vault/items/secret-1"
  SECRET_2: "vaults/vault/items/secret-2"

```

Alternatively would be nice if 1password had a native support key-value pair type secrets built in.

### Is there a workaround to accomplish this today?

Mount every secret individually. This increases boilerplate and reduces readability.
E: Seems that there's a way to mount multiple secrets with one file: https://github.com/1Password/onepassword-operator/pull/60 However, there is still no way to add multiple key / value pairs per secret.

**Comment by jillianwilson** [comment]
Hi there,

The 1Password operator actually can place multiple fields in a secret. When you create a secret using ```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: testing-secrets #this name will also be used for naming the generated kubernetes secret
spec:
  SECRET_1: "vaults/vault/items/secret-1"
```
each field in the 1Password item will become a field in the data of the kubernetes secret. For example if you have a username and password stored in `secret-1` in 1Password. This will translate to the following:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-1
type: Opaque
data:
  username: "base64"
  password: "base64"
```

Is this an acceptable solution for you or is it necessary for you to be able to place multiple 1Password items (and their fields) within a secret?

**Comment by villesau** [comment]
@jillianwilson what happens to `testing-secrets` and `SECRET_1`? And where the `secret-1` comes from? An example in the documentation would probably help to understand this!

**Comment by lhriley** [comment]
@jillianwilson I'm not sure that this is a valid example:
> ```
> apiVersion: onepassword.com/v1
> kind: OnePasswordItem
> metadata:
>   name: testing-secrets #this name will also be used for naming the generated kubernetes secret
> spec:
>   SECRET_1: "vaults/vault/items/secret-1"
> ```

When I specify any key other than `itemPath` I get a validation error. With this in mind, the following example would definitely not work:
 ```
 apiVersion: onepassword.com/v1
 kind: OnePasswordItem
 metadata:
   name: testing-secrets #this name will also be used for naming the generated kubernetes secret
 spec:
   SECRET_1: "vaults/vault/items/secret-1"
   SECRET_2: "vaults/vault/items/secret-2"
 ```
