### ISSUE TITLE
Support secrets with sections containing same key names

### ISSUE THREAD

**Issue by lhriley** [1Password/onepassword-operator#83]
### Summary
Support secrets where section headers delineate related sets of secrets that contain the same keys.

### Use cases
For some use cases, a secret item may contain multiple sections that describe the same kinds of information (keys) with different values. 

For example:
```yaml
username: nosection
password: nosection

sectionA:
  username: foo
  password: foopass

sectionB:
  username: bar
  password: barpass

[...]

sectionZ:
  username: zed
  password: zedpass
```

### Proposed solution
Create secrets based on the section name as a suffix.

For example:
```yaml
mysecret -> no section key / values
mysecret-sectionA -> sectionA key / values
mysecret-sectionB -> sectionB key / values
[...]
mysecret-sectionZ -> sectionZ key / values
```
This should be gate-able via annotations on the `OnePasswordItem` such as:
```
operator.1password.io/secrets-from-sections: <bool>
```
The default behavior should be disabled as sections may not contain duplicate keys.

### Is there a workaround to accomplish this today?
Create separate onepassword secret items and  `OnePasswordItem` for each corresponding section rather than keeping all secrets in a single item. 

Note that currently, for secrets containing sections with the same key names, the last matching key/value pair wins.

### References & Prior Work

* This PR adds support for environment variables by keys in sections: https://github.com/1Password/onepassword-operator/pull/79
