### ISSUE TITLE
Support specifying the secret type

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/onepassword-operator#95]
### Summary

I would like to be able to specify a secret type other than `Opaque`, e.g. `kubernetes.io/dockerconfigjson`.

### Use cases

To use the `imagePullSecrets` feature, a secret must be of type `kubernetes.io/dockerconfigjson`. Currently, deploying a secret as an Opaque doesn't work. 

### Proposed solution

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: secret #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: vaults/***/items/***
  type: kubernetes.io/dockerconfigjson
```

### Is there a workaround to accomplish this today?

Not that I am aware of.

**Comment by tomjohnburton** [comment]
Having looked at the code, I can see that `type` is an available part of the schema for a `OnePasswordItem`. However, if I try to specify that, it fails with validation errors.

**Comment by SimonBarendse** [comment]
I believe this is a duplicate of https://github.com/1Password/onepassword-operator/issues/38 and released in [v1.2.0](https://github.com/1Password/onepassword-operator/releases/tag/v1.2.0).

I'm going to close this as a duplicate. If you need something different from what was released in `v1.2.0`, please reopen this issue.

**Comment by tomjohnburton** [comment]
Hi @SimonBarendse , I just tried to create a secret like so 
```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dockerconfigjson
  namespace: kube-system
  annotations:
    kubed.appscode.com/sync: ""
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: vaults/******/items/******
```

The `itemPath` refers to a `document` type in 1Password. The secret was still generated as `Opaque`.
